### ISSUE TITLE
Price not updated in cart

### ISSUE THREAD

**Issue by AymericJoubert** [Smile-SA/magento2-module-retailer-offer#2]
The price of the items added in cart is not updated after backoffice offer change.

Steps to reproduce : 
- Choose pickup store and pickup date
- Add a product to cart
- In backoffice, change the price of the corresponding offer
-> In the cart, the price is not updated

Also, we need to know when a price is updated in cart, to advise the customer about it (like deleted products).

Regards,
Aymeric

**Comment by romainruaud** [comment]
Fixed by https://github.com/Smile-SA/magento2-module-retailer-offer/commit/c1ef80062ef6482f935e2e2bc95e16a23e68ed91

I added an event which is triggered for each product (meaning you have to collect it via a singleton if you want to display a unique message for all affected products).

The event is smile_retailer_suite_quote_item_price_change
